### ISSUE TITLE
Streamline compilation for Windows

### ISSUE THREAD

**Issue by mikhail-barg** [sequitur-g2p/sequitur-g2p#1]
I'm trying to use sequitur-g2p under Windows and for now it looks like a total pain. It just won't compile C++ code even after installation of ["Microsoft Visual C++ Compiler Package for Python 2.7"](https://www.microsoft.com/en-us/download/details.aspx?id=44266). All it looks like the native code is targeted for GCC only.

I found [this guide](http://mirlab.org/users/davidson.chen/relatedPapers/g2p/g2p_readme.html) with details on using mingw, but the length of it scares me to death. It includes for example manual creation of libpython27.a from python27.dll

So, I'm wondering if you could elaborate on simplifying these steps for Windows users?

**Comment by jtrmal** [comment]
Hi, I have no experience with trying to compile it under windows. At these
times, I don't have the time to try it myself.
You might be able to make it work through cygwin, but again, I don't know
and I won't be probably able to provide much support even though I'd be
glad to help
BTW, Visual Studio 2015 has clang compiler frontend -- you might try that.
I was able to compile it with clang under linux. Perhaps that would be
easier?
y.

**Comment by zarquon5** [comment]
To whom it may concern:

It was clear to me from reading some interweb comments around this package that the code is built specifically for (and assumes) gcc compilation, so I abandoned any hope of compiling this with Visual Studio, and instead installed MinGW as instructed in the [referenced article](http://mirlab.org/users/davidson.chen/relatedPapers/g2p/g2p_readme.html), and managed to compile this under Windows.  I mostly followed the steps in that article, but there are now several issues with those instructions; I've detailed the diversions I had to take from them below...

1. The edit to sequitur.i appears to no longer be necessary, having been fixed in the latest source code.

2. I followed the suggestion of removing the use of -mno-cygwin in lines 322-329 of lib\distutils\cygwincompiler.py, as this option appeared to not/(no longer?) be recognized by the MinGW gcc compiler.

3. cdefs.h is not part of the latest MinGW release either, and the link for the source to cdefs.h in the posted article no longer works, but I found a copy of it [here](http://unix.superglobalmegacorp.com/Net2/newsrc/sys/cdefs.h.html), and placed this file in the MinGW include/sys directory.

4. As far as I can tell, libiberty is no longer available with MinGW either, so I had to remove the need for it.  I therefore skipped the creation and inclusion of "fix.h", and instead edited Assertions.cc to modify line 110 in the function ErrorSignalHandler::handler(int sig) to read:
	  << "signal " << sig << " occurred" << std::endl
That is, I simply output the integer signal number,  rather than referencing the (unavailable) function strsignal() from the missing libiberty library.   
The above change also removes the need to follow the step "Tell python's distutils to link g2p against libiberty.a" too.  (Also, AFAICT, there is no/(no longer?) a setup.cfg for g2p, so his instructions to simply "add a line to the bottom of the file" are now not applicable, and you would need to know which command (link, perhaps?) you were configuring.  But I digress...)

5. I then commented out all of the lines in the function ErrorSignalHandler::ErrorSignalHandler(), since they referred to signals that weren't in MinGW's signal.h file.  

Anyway, the rest of the steps in the [referenced article](http://mirlab.org/users/davidson.chen/relatedPapers/g2p/g2p_readme.html) worked for me, and I was able to build and install the package under my python 2.7 installation.  I don't know the impact of commenting out all the signalling stuff, but I suspect that's not useful for Windows anyway, and the program seems to work.

**Comment by jtrmal** [comment]
Thanks, I'll leave it open for now -- would you consider creating a README.windows (via PR) in the sequitur-g2p repo?

**Comment by Sanbot-okk** [comment]
Hi
I am getting this error with Assertions.cc that says undefined reference to 'strsignal'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\MinGW\\bin\\g++.exe' failed with exit status 1

Can somebody please walk me through the step  "Tell python's distutils to link g2p against libiberty.a"
Because that's the only step i skipped and do not understand.

I tried
editing Assertions.cc to modify line 110 in the function ErrorSignalHandler::handler(int sig) to read:
<< "signal " << sig << " occurred" << std::endl

But that doesn't solve my problem.

**Comment by jtrmal** [comment]
Hi, to address this, I have just finished modification of the infrastructure to get the python wheels installed. Are there any testers willing to give it a go under windows?

**Comment by jtrmal** [comment]
```
pip install -i https://test.pypi.org/simple/ sequitur-g2p
```

**Comment by nullpunktTUD** [comment]
Installed it on Windows 10 using a virtualenv and Python 3.7.3, worked like a charm.

**Comment by jtrmal** [comment]
also pipy should have windows packages now, so I think we can close...
